const siteUrl = 'https://batonbot.com';
const ogImage = `${siteUrl}/og-image.png`;

const description =
  'BatonBot is a kanban board and orchestrator for AI coding agents — like Jira, but your agents work the tickets. Chain native baton-code agents, Aider, Cline, and local LLMs into repeatable, autonomous workflows.';

export const metadata = {
  title: 'BatonBot | Visual Orchestrator for AI Agent Pipelines',
  description,
  keywords: [
    'BatonBot',
    'AI agent orchestrator',
    'visual AI workflow',
    'AI agent pipeline',
    'Aider orchestration',
    'Cline orchestration',
    'LM Studio',
    'local LLM agent',
    'Kanban AI workflow',
    'kanban board for AI agents',
    'Jira for AI agents',
    'AI agent task manager',
    'run multiple AI coding agents',
    'OpenAI compatible proxy',
    'agent chaining',
    'Jira automation',
    'Jira AI agent',
    'task ingress API',
    'portable AI orchestrator',
    'MCP agent server',
    'OpenClaw',
    'open source AI agent',
  ].join(', '),
  canonical: siteUrl,
  og: {
    title: 'BatonBot | Visual Orchestrator for AI Agent Pipelines',
    description,
    image: ogImage,
    url: siteUrl,
    type: 'website',
    siteName: 'BatonBot',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BatonBot | Visual Orchestrator for AI Agent Pipelines',
    description,
    image: ogImage,
    site: '@micdoty',
    creator: '@micdoty',
  },
  robots: 'index, follow',
  author: 'Michael Doty',
  themeColor: '#8B5CF6',
  jsonLd: {
    softwareApplication: {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'BatonBot',
      description,
      operatingSystem: 'macOS, Windows, Linux',
      applicationCategory: 'DeveloperApplication',
      softwareVersion: '3.4.0',
      url: siteUrl,
      featureList: [
        'Drag-and-drop Kanban task board for AI agent sequencing',
        'Native baton-code agents plus Aider, Cline, and Telegram routing',
        'Hybrid LLM support — LM Studio locally or any OpenAI-compatible API',
        'Real-time orchestration via SSE with Play, Pause, and Cancel',
        'Ingress API — POST tasks onto the board from webhooks, CI, or bots',
        'Jira channel — tickets become cards, results are commented back',
        'Portable no-install bundles for Windows x64 and macOS Apple Silicon',
        'Local-first with transparent JSONL logging',
      ],
      license: 'https://opensource.org/licenses/MIT',
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
      },
      author: {
        '@type': 'Person',
        name: 'Michael Doty',
        url: 'https://github.com/mdoty4',
      },
      sameAs: ['https://github.com/mdoty4/batonbot'],
    },
  },
};
